site_name: PyTorch Builder’s Companion Book
site_url: https://github.com/McKlay/pytorch-companion-book/
site_author: Clay Mark Sarte
site_description: A personal PyTorch companion book by Clay Mark Sarte — deep dives into the torch API for learners, devs, and researchers.

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: slate
      primary: deep purple
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
  features:
    - navigation.sections
    - navigation.expand
    - content.code.copy
    - content.code.annotate
    - search.suggest
    - search.highlight
  hide:
    - toc

nav:
  - Table of Contents: index.md

  - "":
      - "&nbsp; Preface": Preface.md
      - "&nbsp;&nbsp; 📖 Part I: Getting Started with torch": PartI_overview.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 1": chapter1_what_is_torch.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 2": chapter2_installation_setup.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 3": chapter3_tensor_fundamentals.md

      - "&nbsp;&nbsp; 📖 Part II: torch API Deep Dive": PartII_overview.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 4": chapter4_tensor.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 5": chapter5_dtype_device.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 6": chapter6_random_seed.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 7": chapter7_math_ops.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 8": chapter8_broadcast_shape.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 9": chapter9_autograd.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 10": chapter10_type_casting.md

      - "&nbsp;&nbsp; 📖 Part III: Special Modules": PartIII_overview.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 11": chapter11_linalg.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 12": chapter12_nn_functional.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 13": chapter13_special.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 14": chapter14_fft.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 15": chapter15_utils.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 16": chapter16_storage_memory.md

      - "&nbsp;&nbsp; 📖 Part IV: Real-World Application": PartIV_overview.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 17": chapter17_cuda.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 18": chapter18_numpy.md
      - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Chapter 19": chapter19_debugging.md

      - "&nbsp;&nbsp; 📖 Appendices":
        - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Tensor Shapes": appendix_shapes.md
        - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Idioms & Gotchas": appendix_idioms.md
        - "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; API Reference": appendix_api_reference.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - footnotes
  - codehilite
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/McKlay
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/clay-mark-sarte-283855147/